# Generated by Django 4.2.6 on 2023-10-18 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiPost', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoID', models.CharField(max_length=2)),
                ('numeroID', models.BigIntegerField()),
                ('nombre', models.CharField(max_length=250)),
                ('apellido', models.CharField(max_length=250)),
                ('genero', models.CharField(max_length=10)),
                ('rol', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=50)),
                ('contrasenia', models.CharField(max_length=80)),
            ],
        ),
        migrations.DeleteModel(
            name='login',
        ),
        migrations.DeleteModel(
            name='register',
        ),
    ]
